#server:
#  port: 8081
#
#spring:
#  devtools:
#    livereload:
#      enabled: false
#    restart:
#      enabled: false
#  datasource:
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://localhost:3306/oauth2?serverTimezone-UTC&chracterEncoding=UTF-8
#      username: han
#      password: 1q2w3e4r!
      
   
 # security:
 #   user:
 #    name: handg
 #    password: 1111
  